### PR TITLE
merge latest Mintr changes into StakeDAO

### PR DESCRIPTION
**Pull request by leopoldjoy**

### CODE REVIEW

**Comment by bneiluj** [comment]
Why are the .svg modified ? Is it because of linting?

**Comment by leopoldjoy** [comment]
> Why are the .svg modified ? Is it because of linting?

These changes came from the latest Mintr repo commits: https://github.com/stake-capital/stakeDAO/pull/14/commits

**Comment by bneiluj** [comment]
What is the past transaction component empty ? 
Screenshot 2020-05-01 at 17 48 29

**Comment by bneiluj** [comment]
Also got this bug at some point but don't remember how...But memory is URGENT matter ahahaha 
Screenshot 2020-05-01 at 17 44 30

**Comment by leopoldjoy** [comment]
> What is the past transaction component empty ?
> Screenshot 2020-05-01 at 17 48 29

Because you don't have any past transactions. We could display a message there when empty, let's add a separate ticket for that?

**Comment by leopoldjoy** [comment]
> Also got this bug at some point but don't remember how...But memory is URGENT matter ahahaha
> Screenshot 2020-05-01 at 17 44 30

The leak's stack trace references `NotificationCenter.js:15` which is a notifications component which was not altered for the StakeDAO repo. Let's open an issue on the underlying [`synthetix-mintr` repo](https://github.com/Synthetixio/synthetix-mintr/issues)?

**Comment by bneiluj** [comment]
Ive made a lot of tx's using that address so the components should display tx's there. It was showing tx's before.

**Comment by leopoldjoy** [comment]
> Ive made a lot of tx's using that address so the components should display tx's there. It was showing tx's before.

Ok, got it, was able to replicate! It was a simple bug caused by the `BalanceTable` component waiting for extraneous data to load (old data used by the Mintr parent repo). Commit pushed [here](https://github.com/stake-capital/stakeDAO/pull/14/commits/363ea42146464179dce23f72c470696f8fc74ccd). 👍

**Comment by bneiluj** [comment]
Screenshot 2020-05-05 at 11 15 16
Screenshot 2020-05-05 at 11 15 32

**Pull request merged**
